BEGIN;

DROP TRIGGER IF EXISTS set_updated_at ON "users";
DROP TRIGGER IF EXISTS set_updated_at ON "notes";

DROP FUNCTION IF EXISTS set_updated_at_column;

DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "notes" CASCADE;
DROP TABLE IF EXISTS "codes" CASCADE;
DROP TABLE IF EXISTS "images" CASCADE;

COMMIT;

ROLLBACK;